name: BukkitPiano
version: 1.0
main: me.glatteis.bukkitpiano.server.ServerMain
authors: [glatteis,avixk]
api-version: 1.13
commands:
  bukkitpiano:
    usage: /bukkitpiano
    description: BukkitPiano main command
    permission: piano.play