name: BukkitPiano
version: 2.0
main: me.glatteis.bukkitpiano.server.ServerMain
authors: [glatteis,avixk]
api-version: 1.13
commands:
  bukkitpiano:
    usage: /bukkitpiano
    aliases: [piano]
    description: BukkitPiano main command
    permission: bukkitpiano.use